- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "Accessibility"
  url: "/accessibility/"
  title: "Accessibility"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
